// GeoExchange — Tailwind theme configuration
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#2c344d",
        "inverse-surface": "#dbe1ff",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#050d25",
        "error-container": "#93000a",
        "on-tertiary": "#213145",
        "on-background": "#dbe1ff",
        "surface-container-low": "#131a33",
        "surface-dim": "#0a122a",
        secondary: "#bdc5e9",
        "tertiary-container": "#94a4bd",
        "on-primary-container": "#00422b",
        "surface-container-high": "#212942",
        tertiary: "#b7c8e1",
        "primary-fixed-dim": "#4edea3",
        primary: "#4edea3",
        "surface-variant": "#2c344d",
        surface: "#0a122a",
        "on-primary-fixed-variant": "#005236",
        error: "#ffb4ab",
        "inverse-primary": "#006c49",
        outline: "#86948a",
        "on-primary-fixed": "#002113",
        "on-error": "#690005",
        "secondary-fixed-dim": "#bdc5e9",
        "outline-variant": "#3c4a42",
        "inverse-on-surface": "#282f49",
        "on-secondary": "#262f4c",
        "secondary-fixed": "#dbe1ff",
        "surface-container": "#171e37",
        "on-tertiary-fixed": "#0b1c30",
        "on-tertiary-fixed-variant": "#38485d",
        "primary-container": "#10b981",
        "secondary-container": "#3d4664",
        "on-primary": "#003824",
        "on-secondary-fixed": "#111a36",
        "surface-bright": "#313852",
        "on-secondary-container": "#abb4d7",
        "on-secondary-fixed-variant": "#3d4664",
        "on-surface-variant": "#bbcabf",
        "tertiary-fixed": "#d3e4fe",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-tertiary-container": "#2a3a4f",
        background: "#0a122a",
        "primary-fixed": "#6ffbbe",
        "on-surface": "#dbe1ff",
        "surface-tint": "#4edea3",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-3xl": "4rem",
        "space-xl": "2rem",
        "space-xs": "0.5rem",
        "layout-margin-mobile": "1rem",
        "space-sm": "0.75rem",
        "space-lg": "1.5rem",
        "space-2xs": "0.25rem",
        "space-2xl": "3rem",
        "layout-margin-desktop": "2.5rem",
        "space-md": "1rem",
        "layout-gutter": "1rem",
        "layout-margin-tablet": "1.5rem",
      },
      fontFamily: {
        "headline-xl": ["Inter"],
        "label-meta": ["Noto Sans"],
        "label-numeric": ["Inter"],
        "headline-sm": ["Inter"],
        "body-lg": ["Noto Sans"],
        "headline-xl-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "body-sm": ["Noto Sans"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Noto Sans"],
        "label-ticker": ["Inter"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-meta": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-numeric": ["16px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-xl-mobile": ["30px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-ticker": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
};
